services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: hiking_postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-hiking}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hiking_api
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-hiking}
    volumes:
      - ./api:/app
      - ./uploads:/app/uploads
    depends_on:
      - postgis

  web:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: hiking_app_ui
    ports:
      - 3000:80
    depends_on:
      - api
    restart: always
